/*
  Automatically generated by Autodist 1.4.  Do not edit.

  Generated: Sat Sep 26 23:32:29 EEST 2009 by priikone
  Distribution: Server
  License: 
*/

#ifndef _SILC_DISTDEFS_H
#define _SILC_DISTDEFS_H

#define SILC_DIST_APPS 1
#define SILC_DIST_ASN1 1
#define SILC_DIST_COMPILER 1
#define SILC_DIST_CRYPTO 1
#define SILC_DIST_DOC 1
#define SILC_DIST_HTTP 1
#define SILC_DIST_IDCACHE 1
#define SILC_DIST_INCLUDES 1
#define SILC_DIST_LIB 1
#define SILC_DIST_MATH 1
#define SILC_DIST_SERVER 1
#define SILC_DIST_SILC 1
#define SILC_DIST_SKR 1
#define SILC_DIST_TMA 1

#endif /* _SILC_DISTDEFS_H */
